spring:
  datasource:
#    url: jdbc:mysql://${RDS_ENDPOINT}:3306/${DB_NAME}
    url: ${RDS_DB_URL}
    username: ${RDS_DB_ID}
    password: ${RDS_DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


aws:
  s3:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}
    bucket-name: ${S3_BUCKET_NAME}

flask:
  api:
    url: ${FLASK_API_URL}

server:
  port: 8080
